lang_dict = {
    'zh': {
        # 通用
        'home': '首页',
        'login_now': '立即登录',
        'register_btn': '注册',
        'profile': '个人资料',
        'logout': '退出登录',
        'logout_confirm': '确定要退出登录吗？',
        'filter': '筛选',
        'reset': '重置',
        'detail': '详情',
        'back_to_list': '返回列表',

        # 菜单相关
        'store_manage': '店铺管理',
        'sales_manage': '营业管理',
        'store_renovation': '店铺整改',
        'report_center': '报表中心',
        'attendance_punch': '考勤打卡',
        'system_manage': '系统管理',
        'user_manage': '用户管理',

        # 物料盘点
        'inventory_stocktake': '物料盘点',

        # 报表子项
        'sales_daily': '销售日报',
        'sales_weekly': '销售周报',
        'sales_monthly': '销售月报',
        'cost_reports': '营业信息统计',
        'profit_loss': '损益报表',
        'sales_summary': '销售额统计',

        # 整改模块
        'renovation_list': '整改任务列表',
        'renovation_create': '创建整改任务',
        'renovation_detail': '整改任务详情',
        'task_status': '任务状态',
        'task_priority': '优先级',
        'responsible_store': '责任门店',
        'responsible_person': '责任人',
        'search_tasks': '搜索任务',
        'task_title': '任务标题',
        'due_date': '截止时间',
        'created_date': '创建时间',
        'priority_urgent': '紧急',
        'priority_high': '高',
        'priority_medium': '中',
        'priority_low': '低',
        'priority_urgent': '紧急',
        'priority_high': '高',
        'priority_medium': '中',
        'priority_low': '低',
        # 验收结果
        'verification_passed': '验收通过',
        'verification_failed': '验收不通过',
        'task_status_pending': '待处理',
        'task_status_processing': '进行中',
        'task_status_awaiting_verification': '待验收',
        'task_status_completed': '已完成',
        'task_status_closed': '已关闭',
        'task_status_rejected': '已驳回',
        'overdue': '已逾期',
        'days_remaining': '天剩余',
        'upload_evidence': '上传证据',
        'verify_task': '验收任务',

        # 额外翻译（renovation 模块补充）
        'action': '操作',
        'all_status': '全部状态',
        'all_stores': '全部门店',
        'close_task': '关闭任务',
        'completed_date': '完成时间',
        'download_attachment': '下载附件',
        'file_attachments': '文件附件',
        'filter_by_priority': '按优先级筛选',
        'improvement_evidence': '改进证据',
        'no_attachments': '无附件',
        'no_key_change_history': '无关键变更记录',
        'problem_description': '问题描述',
        'renovation_task': '整改任务',
        'reopen_task': '重新打开任务',
        'return': '返回',
        'task_records': '任务记录',
        'task_verification': '任务验收',
        'this_month': '本月',
        'this_week': '本周',
        'time': '时间',
        'today': '今日',
        'verification_comments': '验收意见',
        'verifier': '验收人',
        'evidence_submitted_awaiting_verification': '整改证据已提交，等待验收',
        'submit_failed_try_again': '提交失败，请重试',

        # 分类翻译（renovation 默认分类）
        'category_hygiene': '卫生问题',
        'category_equipment': '设备维护',
        'category_service': '服务质量',
        'category_safety': '安全隐患',
        'category_other': '其他问题',
        # JS 文本
        'no_branch_manager': '无分店长',

        # 分页
        'prev_page': '上一页',
        'next_page': '下一页',

        # 报销相关（常用）
        'reimbursement': '财务报销',
        'reimbursement_no_data': '暂无数据',
        # 报销核对相关
        'mark_checked': '标记已核对',
        'reimbursement_checked': '已核对',
        'reimbursement_unchecked': '未核对',
        'reimbursement_check_status': '核对状态',

        # 报销列表页面
        'reimbursement_list_title': '报销申请列表',
        'reimbursement_finance': '财务',
        'reimbursement_create_title': '创建报销申请',
        'reimbursement_create_btn': '新建报销申请',
        'reimbursement_mine': '我的申请',
        'reimbursement_all': '全部申请',
        'reimbursement_todo': '待审批',
        'reimbursement_done': '已审批',
        'reimbursement_cc_to_me': '抄送给我',
        'reimbursement_all_time': '全部时间',
        'reimbursement_recent_24h': '最近24小时',
        'reimbursement_recent_7d': '最近7天',
        'reimbursement_recent_30d': '最近30天',
        'reimbursement_custom_date': '自定义日期',
        'reimbursement_query_btn': '查询',

        # 表格列
        'reimbursement_submission_date': '提交日期',
        'store_id_column': '门店ID',
        'reimbursement_submitter': '提交人',
        'reimbursement_approver': '审批人',
        'reimbursement_search_approver': '搜索审批人',
        'cc_recipients_optional': '抄送人（可选）',
        'search_and_add_cc': '搜索并添加抄送人',
        'can_add_multiple_cc': '可以添加多个抄送人',
        'system_auto_cc_default': '系统会自动抄送默认抄送人',
        'manage_default_cc': '管理默认抄送人',
        'reimbursement_attachments': '附件',
        'reimbursement_attachment_tip': '支持上传多个文件（图片、PDF等）',
        'reimbursement_attachment_preview_modal_title': '附件预览',
        'reimbursement_category_shared_reimbursement': '公摊报销',
        'reimbursement_category_agency_accounting': '代理记账',
        'reimbursement_category_taxes': '各种税费',
        'reimbursement_category_employee_social_security': '员工社保',
        'reimbursement_category_store_management': '店铺管理',
        'reimbursement_category_other_shared_cost': '其它公摊',
        'reimbursement_category_mixture_material': '蜜雪物料',
        'reimbursement_category_material_transport': '物料运输',
        'reimbursement_category_fixed_salary': '固定工资',
        'reimbursement_category_temporary_salary': '临时工工资',
        'reimbursement_category_external_lemon': '外部柠檬',
        'reimbursement_category_store_petty_cash': '店铺备用金',
        'reimbursement_category_rental_tax': '租房税',
        'reimbursement_category_utilities': '水电费',
        'reimbursement_category_store_rent': '店铺房租',
        'reimbursement_category_warehouse_rent': '仓库房租',
        'reimbursement_category_other_cost': '其它成本',
        'reimbursement_amount': '金额',
        'reimbursement_currency': '货币',
        'reimbursement_reason': '事由',
        'reimbursement_primary_category': '一级分类',
        'reimbursement_secondary_category': '二级分类',
        'reimbursement_status': '状态',
        'SHARED_COST': '公摊成本',

        # 状态
        'reimbursement_pending': '待审批',
        'reimbursement_approved': '已通过',
        'reimbursement_rejected': '已驳回',
        'reimbursement_draft': '草稿',

        # 操作按钮
        'reimbursement_detail_btn': '详情',
        'reimbursement_approve_btn': '审批',
        'reimbursement_transfer': '转交',
        'withdraw_btn': '撤回',
        'reimbursement_edit': '编辑',
        'reimbursement_delete': '删除',
        'reimbursement_action': '操作',
        'reimbursement_back_to_list': '返回列表',
        'reimbursement_preview': '预览',
        'reimbursement_preview_modal_title': '附件预览',

        # 确认消息
        'confirm_withdraw_msg': '确定要撤回此申请吗？',
        'confirm_delete_draft_msg': '确定要删除此草稿吗？',

        # 转交弹窗
        'transfer_approver': '转交审批人',
        'close': '关闭',
        'search_approver_finance_admin_only': '搜索审批人（仅限财务/管理员）',
        'enter_name_account_phone': '输入姓名/账号/手机号',
        'cancel': '取消',
        'confirm_transfer': '确认转交',

        # 审批页面
        'reimbursement_approval_title': '报销审批',
        'reimbursement_application_info': '申请信息',
        'reimbursement_id': '申请ID',
        'reimbursement_store': '门店',
        'reimbursement_reason': '事由',
        'reimbursement_cc_recipients': '抄送人',
        'reimbursement_related_attachments': '相关附件',
        'reimbursement_attachment': '附件',
        'reimbursement_attachment_preview': '附件预览',
        'preview': '预览',
        'reimbursement_approval_operation': '审批操作',
        'reimbursement_upload_attachments_tips': '请上传审批相关附件（如发票、收据等）',
        'reimbursement_approval_pass': '通过',
        'reimbursement_return': '返回',

        # 管理功能
        'all_reimbursement': '全部报销申请',
        'email_settings': '邮件设置',
        'email_logs': '邮件发送日志',
        'default_cc_config_title': '默认抄送人配置',
        'system_management_badge': '系统管理',
        'back_to_reimbursement_list': '返回报销列表',
        'explanation': '说明',
        'default_cc_explanation': '配置默认抄送人后，新建报销申请时会自动添加这些人为抄送人',
        'add_default_cc_title': '添加默认抄送人',
        'search_user_label': '搜索用户',
        'search_user_placeholder': '输入用户名、姓名或工号',
        'add_as_default_cc_btn': '添加为默认抄送人',
        'current_default_cc_title': '当前默认抄送人',
        'people_count': '人',
        'user_id': '用户ID',
        'username': '用户名',
        'real_name': '真实姓名',
        'role': '角色',
        'role_admin': '管理员',
        'role_head_manager': '总店长',
        'role_finance': '财务',
        'role_branch_manager': '分店长',
        'role_employee': '店员',
        'email': '邮箱',
        'add_time': '添加时间',
        'added_by': '添加人',
        'operation': '操作',
        'confirm_disable_default_cc': '确定要禁用此默认抄送人吗？',
        'disable': '禁用',
        'no_default_cc_config': '暂无默认抄送人配置',
        # 货币
        'currency_thb': '泰铢',
        'currency_cny': '人民币',
        'attendance_clock_in': '上班打卡',
        'attendance_clock_out': '下班打卡',
    },

    'th': {
        # Common
        'home': 'หน้าแรก',
        'login_now': 'เข้าสู่ระบบทันที',
        'register_btn': 'สมัครสมาชิก',
        'profile': 'ข้อมูลส่วนตัว',
        'logout': 'ออกจากระบบ',
        'logout_confirm': 'คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?',
        'filter': 'กรอง',
        'reset': 'รีเซ็ต',
        'detail': 'รายละเอียด',
        'back_to_list': 'กลับสู่รายการ',

        # Menu
        'store_manage': 'จัดการสาขา',
        'sales_manage': 'จัดการยอดขาย',
        'store_renovation': 'การปรับปรุงสาขา',
        'report_center': 'ศูนย์รายงาน',
        'attendance_punch': 'บันทึกเวลาเข้างาน',
        'system_manage': 'การจัดการระบบ',
        'user_manage': 'การจัดการผู้ใช้',

        # 物料盘点
        'inventory_stocktake': 'ตรวจนับสต็อกวัสดุ',

        # Reports
        'sales_daily': 'รายงานประจำวัน',
        'sales_weekly': 'รายงานประจำสัปดาห์',
        'sales_monthly': 'รายงานประจำเดือน',
        'cost_reports': 'สถิติค่าใช้จ่าย',
        'profit_loss': 'งบกำไรขาดทุน',
        'sales_summary': 'สถิติยอดขาย',

        # Renovation
        'renovation_list': 'รายการงานปรับปรุง',
        'renovation_create': 'สร้างงานปรับปรุง',
        'renovation_detail': 'รายละเอียดงานปรับปรุง',
        'task_status': 'สถานะงาน',
        'task_priority': 'ความสำคัญ',
        'responsible_store': 'สาขาที่รับผิดชอบ',
        'responsible_person': 'ผู้รับผิดชอบ',
        'search_tasks': 'ค้นหางาน',
        'task_title': 'หัวข้องาน',
        'due_date': 'วันที่ครบกำหนด',
        'created_date': 'วันที่สร้าง',
        'priority_urgent': 'ด่วน',
        'priority_high': 'สูง',
        'priority_medium': 'ปานกลาง',
        'priority_low': 'ต่ำ',
        'priority_urgent': 'ด่วน',
        'priority_high': 'สูง',
        'priority_medium': 'ปานกลาง',
        'priority_low': 'ต่ำ',
        # 验收结果（泰文）
        'verification_passed': 'ตรวจรับผ่าน',
        'verification_failed': 'ตรวจรับไม่ผ่าน',
        'task_status_pending': 'รอดำเนินการ',
        'task_status_processing': 'กำลังดำเนินการ',
        'task_status_awaiting_verification': 'รอตรวจสอบ',
        'task_status_completed': 'เสร็จแล้ว',
        'task_status_closed': 'ปิดแล้ว',
        'task_status_rejected': 'ถูกปฏิเสธ',
        'overdue': 'เกินกำหนด',
        'days_remaining': 'วันที่เหลือ',
        'upload_evidence': 'อัปโหลดหลักฐาน',
        'verify_task': 'ตรวจรับงาน',
        'evidence_description': 'คำอธิบายหลักฐาน',
        'evidence_description_placeholder': 'โปรดอธิบายมาตรการและผลลัพธ์การปรับปรุงของคุณ...',

        # เพิ่มเติม (renovation 模块)
        'action': 'การดำเนินการ',
        'all_status': 'สถานะทั้งหมด',
        'all_stores': 'ทุกสาขา',
        'close_task': 'ปิดงาน',
        'completed_date': 'วันที่เสร็จสิ้น',
        'download_attachment': 'ดาวน์โหลดเอกสารแนบ',
        'file_attachments': 'เอกสารแนบ',
        'filter_by_priority': 'กรองตามความสำคัญ',
        'improvement_evidence': 'หลักฐานการปรับปรุง',
        'no_attachments': 'ไม่มีไฟล์แนบ',
        'no_key_change_history': 'ไม่มีประวัติการเปลี่ยนแปลงสำคัญ',
        'problem_description': 'คำอธิบายปัญหา',
        'renovation_task': 'งานปรับปรุง',
        'reopen_task': 'เปิดงานอีกครั้ง',
        'return': 'กลับ',
        'task_records': 'บันทึกงาน',
        'task_verification': 'การตรวจรับงาน',
        'this_month': 'เดือนนี้',
        'this_week': 'สัปดาห์นี้',
        'time': 'เวลา',
        'today': 'วันนี้',
        'verification_comments': 'ความคิดเห็นการตรวจรับ',
        'verifier': 'ผู้ตรวจรับ',
        'evidence_submitted_awaiting_verification': 'ส่งหลักฐานการปรับปรุงแล้ว รอการตรวจรับ',
        'submit_failed_try_again': 'ส่งล้มเหลว โปรดลองอีกครั้ง',

        # 分类翻译（renovation 默认分类）
        'category_hygiene': 'ปัญหาด้านความสะอาด',
        'category_equipment': 'การบำรุงรักษาอุปกรณ์',
        'category_service': 'คุณภาพการบริการ',
        'category_safety': 'ความเสี่ยงด้านความปลอดภัย',
        'category_other': 'ปัญหาอื่นๆ',
        # JS 文本
        'no_branch_manager': 'ไม่มีหัวหน้าสาขา',

        # Pagination
        'prev_page': 'หน้าก่อนหน้า',
        'next_page': 'หน้าถัดไป',

        # Reimbursement
        'reimbursement': 'การเบิกจ่ายการเงิน',
        'reimbursement_no_data': 'ไม่มีข้อมูล',
        # 报销核对相关（泰文）
        'mark_checked': 'ทำเครื่องหมายว่าตรวจสอบแล้ว',
        'reimbursement_checked': 'ตรวจสอบแล้ว',
        'reimbursement_unchecked': 'ยังไม่ตรวจสอบ',
        'reimbursement_check_status': 'สถานะการตรวจสอบ',

        # 报销列表页面（泰文）
        'reimbursement_list_title': 'รายการคำขอเบิกจ่าย',
        'reimbursement_finance': 'การเงิน',
        'reimbursement_create_title': 'สร้างคำขอเบิกจ่าย',
        'reimbursement_create_btn': 'สร้างคำขอเบิกจ่ายใหม่',
        'reimbursement_mine': 'คำขอของฉัน',
        'reimbursement_all': 'คำขอทั้งหมด',
        'reimbursement_todo': 'รอดำเนินการ',
        'reimbursement_done': 'ดำเนินการแล้ว',
        'reimbursement_cc_to_me': 'ส่งถึงฉัน',
        'reimbursement_all_time': 'เวลาทั้งหมด',
        'reimbursement_recent_24h': '24 ชั่วโมงล่าสุด',
        'reimbursement_recent_7d': '7 วันล่าสุด',
        'reimbursement_recent_30d': '30 วันล่าสุด',
        'reimbursement_custom_date': 'วันที่กำหนดเอง',
        'reimbursement_query_btn': 'ค้นหา',

        # 表格列（泰文）
        'reimbursement_submission_date': 'วันที่ส่ง',
        'store_id_column': 'รหัสร้านค้า',
        'reimbursement_submitter': 'ผู้ส่ง',
        'reimbursement_approver': 'ผู้อนุมัติ',
        'reimbursement_search_approver': 'ค้นหาผู้อนุมัติ',
        'cc_recipients_optional': 'ผู้รับสำเนา (ไม่บังคับ)',
        'search_and_add_cc': 'ค้นหาและเพิ่มผู้รับสำเนา',
        'can_add_multiple_cc': 'สามารถเพิ่มผู้รับสำเนาหลายคน',
        'system_auto_cc_default': 'ระบบจะส่งสำเนาให้ผู้รับสำเนาเริ่มต้นโดยอัตโนมัติ',
        'manage_default_cc': 'จัดการผู้รับสำเนาเริ่มต้น',
        'reimbursement_attachments': 'เอกสารแนบ',
        'reimbursement_attachment_tip': 'รองรับการอัปโหลดไฟล์หลายไฟล์ (รูปภาพ, PDF ฯลฯ)',
        'reimbursement_attachment_preview_modal_title': 'ดูเอกสารแนบ',
        'reimbursement_category_shared_reimbursement': 'เบิกจ่ายต้นทุนร่วม',
        'reimbursement_category_agency_accounting': 'บัญชีตัวแทน',
        'reimbursement_category_taxes': 'ภาษีต่างๆ',
        'reimbursement_category_employee_social_security': 'ประกันสังคมพนักงาน',
        'reimbursement_category_store_management': 'การจัดการร้านค้า',
        'reimbursement_category_other_shared_cost': 'ต้นทุนร่วมอื่นๆ',
        'reimbursement_category_mixture_material': 'วัสดุมิกซ์เชอร์',
        'reimbursement_category_material_transport': 'การขนส่งวัสดุ',
        'reimbursement_category_fixed_salary': 'เงินเดือนคงที่',
        'reimbursement_category_temporary_salary': 'เงินเดือนพนักงานชั่วคราว',
        'reimbursement_category_external_lemon': 'เลมอนภายนอก',
        'reimbursement_category_store_petty_cash': 'เงินสดสำรองร้านค้า',
        'reimbursement_category_rental_tax': 'ภาษีเช่าบ้าน',
        'reimbursement_category_utilities': 'ค่าน้ำค่าไฟ',
        'reimbursement_category_store_rent': 'ค่าเช่าร้านค้า',
        'reimbursement_category_warehouse_rent': 'ค่าเช่าคลังสินค้า',
        'reimbursement_category_other_cost': 'ต้นทุนอื่นๆ',
        'reimbursement_amount': 'จำนวนเงิน',
        'reimbursement_currency': 'สกุลเงิน',
        'reimbursement_reason': 'เหตุผล',
        'reimbursement_primary_category': 'หมวดหมู่หลัก',
        'reimbursement_secondary_category': 'หมวดหมู่ย่อย',
        'reimbursement_status': 'สถานะ',
        'SHARED_COST': 'ต้นทุนร่วม',

        # 状态（泰文）
        'reimbursement_pending': 'รอดำเนินการ',
        'reimbursement_approved': 'อนุมัติแล้ว',
        'reimbursement_rejected': 'ถูกปฏิเสธ',
        'reimbursement_draft': 'ร่าง',

        # 操作按钮（泰文）
        'reimbursement_detail_btn': 'รายละเอียด',
        'reimbursement_approve_btn': 'อนุมัติ',
        'reimbursement_transfer': 'โอน',
        'withdraw_btn': 'ถอน',
        'reimbursement_edit': 'แก้ไข',
        'reimbursement_delete': 'ลบ',
        'reimbursement_action': 'การดำเนินการ',
        'reimbursement_preview': 'ดูตัวอย่าง',
        'reimbursement_preview_modal_title': 'ดูเอกสารแนบ',

        # 确认消息（泰文）
        'confirm_withdraw_msg': 'คุณแน่ใจหรือไม่ว่าต้องการถอนคำขอนี้?',
        'confirm_delete_draft_msg': 'คุณแน่ใจหรือไม่ว่าต้องการลบร่างนี้?',

        # 转交弹窗（泰文）
        'transfer_approver': 'โอนผู้อนุมัติ',
        'close': 'ปิด',
        'search_approver_finance_admin_only': 'ค้นหาผู้อนุมัติ (เฉพาะการเงิน/ผู้ดูแลระบบ)',
        'enter_name_account_phone': 'ป้อนชื่อ/บัญชี/หมายเลขโทรศัพท์',
        'cancel': 'ยกเลิก',
        'confirm_transfer': 'ยืนยันการโอน',

        # 审批页面（泰文）
        'reimbursement_approval_title': 'การอนุมัติเบิกจ่าย',
        'reimbursement_application_info': 'ข้อมูลคำขอ',
        'reimbursement_id': 'รหัสคำขอ',
        'reimbursement_store': 'ร้านค้า',
        'reimbursement_reason': 'เหตุผล',
        'reimbursement_cc_recipients': 'ผู้รับสำเนา',
        'reimbursement_related_attachments': 'เอกสารแนบที่เกี่ยวข้อง',
        'reimbursement_attachment': 'เอกสารแนบ',
        'reimbursement_attachment_preview': 'ดูเอกสารแนบ',
        'preview': 'ดูตัวอย่าง',
        'reimbursement_approval_operation': 'การดำเนินการอนุมัติ',
        'reimbursement_upload_attachments_tips': 'กรุณาอัปโหลดเอกสารแนบที่เกี่ยวข้องกับการอนุมัติ (เช่น ใบแจ้งหนี้ ใบเสร็จรับเงิน ฯลฯ)',
        'reimbursement_approval_pass': 'ผ่าน',
        'reimbursement_return': 'กลับ',

        # 管理功能（泰文）
        'all_reimbursement': 'คำขอเบิกจ่ายทั้งหมด',
        'email_settings': 'การตั้งค่าอีเมล',
        'email_logs': 'บันทึกการส่งอีเมล',
        'default_cc_config_title': 'การกำหนดค่าผู้รับสำเนาเริ่มต้น',
        'system_management_badge': 'การจัดการระบบ',
        'back_to_reimbursement_list': 'กลับไปยังรายการเบิกจ่าย',
        'explanation': 'คำอธิบาย',
        'default_cc_explanation': 'หลังจากกำหนดค่าผู้รับสำเนาเริ่มต้นแล้ว ระบบจะเพิ่มบุคคลเหล่านี้เป็นผู้รับสำเนาโดยอัตโนมัติเมื่อสร้างคำขอเบิกจ่ายใหม่',
        'add_default_cc_title': 'เพิ่มผู้รับสำเนาเริ่มต้น',
        'search_user_label': 'ค้นหาผู้ใช้',
        'search_user_placeholder': 'ป้อนชื่อผู้ใช้, ชื่อจริง หรือรหัสพนักงาน',
        'add_as_default_cc_btn': 'เพิ่มเป็นผู้รับสำเนาเริ่มต้น',
        'current_default_cc_title': 'ผู้รับสำเนาเริ่มต้นปัจจุบัน',
        'people_count': 'คน',
        'user_id': 'รหัสผู้ใช้',
        'username': 'ชื่อผู้ใช้',
        'real_name': 'ชื่อจริง',
        'role': 'บทบาท',
        'role_admin': 'ผู้ดูแลระบบ',
        'role_head_manager': 'ผู้จัดการสาขาใหญ่',
        'role_finance': 'การเงิน',
        'role_branch_manager': 'ผู้จัดการสาขา',
        'role_employee': 'พนักงาน',
        'email': 'อีเมล',
        'add_time': 'เวลาที่เพิ่ม',
        'added_by': 'ผู้เพิ่ม',
        'operation': 'การดำเนินการ',
        'confirm_disable_default_cc': 'คุณแน่ใจหรือไม่ว่าต้องการปิดใช้งานผู้รับสำเนาเริ่มต้นนี้?',
        'disable': 'ปิดใช้งาน',
        'no_default_cc_config': 'ไม่มีผู้รับสำเนาเริ่มต้นที่กำหนดค่าไว้',
        # สกุลเงิน
        'currency_thb': 'บาทไทย',
        'currency_cny': 'หยวนจีน',
        'attendance_clock_in': 'เข้างาน',
        'attendance_clock_out': 'เลิกงาน',
    },
}
