lang_dict = {
    'zh': {
        'role': '角色',
        'store_id': '所属门店',
        'select_store': '请选择门店',
        'employee_number': '员工编号',
        'employee_number_placeholder': '如 91001',
        'employee_number_tip': '请手动输入员工编号（如：店铺编号+三位序号，例如91001）。',
        'username': '用户名',
        'password': '密码',
        'confirm_password': '确认密码',
        'register_title': '新用户注册',
        'register_btn': '注册',
        'already_have_account': '已经有账户了？',
        'login_now': '立即登录',
        'login_title': '用户登录',
        'login_welcome': '欢迎回来',
        'login_subtitle': '请登录您的账户',
        'remember_me': '记住我',
        'login_btn': '登录',
        'no_account': '还没有账户？',
        'register_now': '立即注册',
        'profile_title': '个人资料',
        'profile_subtitle': '我的资料',
        'role_admin': '管理员',
        'role_finance': '财务',
        'role_head_manager': '店长',
        'role_staff': '员工',
        'role_unset': '未设置角色',
        'unknown': '未知',
        'join_year': '加入年份',
        'related_store': '关联门店',
        'profile_completion': '资料完善度',
        'completed': '项已完成',
        'quick_actions': '快捷操作',
        'edit_profile': '编辑资料',
        'change_password': '修改密码',
        'change_password_tip': '密码修改功能待开发',
        'basic_info': '基本信息',
        'real_name': '真实姓名',
        'not_filled': '未填写',
        'not_assigned': '未分配',
        'id_card_number': '身份证号',
        'register_time': '注册时间',
        'work_info': '工作信息',
        'start_date': '入职日期',
        'end_date': '离职日期',
        'on_job': '在职',
        'is_primary_contact': '主要联系人',
        'yes': '✔ 是',
        'no': '❌ 否',
        'contact_info': '联系方式',
        'phone': '联系电话',
        'email': '电子邮箱',
        'bank_info': '银行信息',
        'bank_name': '银行名称',
        'bank_account_number': '银行账号',
        'employee_number_admin_only': '此字段由管理员分配，无法自行修改',
        'unassigned': '未分配',
        'sales_check_title': '营业信息核对',
        'sales_check_bi': 'BI营业核对',
        'report_user': '上报人',
        'pos_sales_info': 'POS机销售信息',
        'cash_income': '现金收入 (C)',
        'pos_income': '电子支付收入 (P)',
        'voucher_amount': '代金券使用金额 (R)',
        'sales_slip_image': 'POS机营业信息凭证',
        'third_party_sales_info': '第三方外卖平台销售信息',
        'takeaway_amount': '第三方外卖平台收入 (T1)',
        'takeaway_platform_receipt': '第三方外卖平台收入凭证',
        'actual_sales_info': '实际入账信息',
        'electronic_actual_arrival': '电子支付实际入账金额 (EA)',
        'electronic_actual_arrival_receipt': '电子支付入账凭证',
        'bank_receipt_image': '银行存款凭证',
        'save_daily_report': '保存日报',
        'save': '保存',
        'edit': '修改',
        'detail': '详情',
        'filter': '筛选',
        'approved': '已审核',
        'pending': '待审核',
        'all_status': '全部',
        'all_stores': '全部门店',
        'finance_remark': '财务备注',
        'finance_remark_placeholder': '可填写财务审核备注',
        'no_remark': '暂无备注',
        'key_change_history': '关键字段修改历史',
        'field': '字段',
        'old_value': '原值',
        'new_value': '新值',
        'operator': '操作人',
        'reason': '理由',
        'time': '时间',
        'no_key_change_history': '暂无关键字段修改历史',
        'daily_voucher': '日报凭证',
        'voucher_img': '凭证图片',
        'pdf_preview': 'PDF预览',
        'file': '文件',
        'no_voucher': '暂无凭证',
        'prev_page': '上一页',
        'next_page': '下一页',
        'page_info': '第',
        'page': '页',
        'daily_report': '营业日报',
        'sales_manage_list_title': '营业信息管理列表',
        'action': '操作',
        'actual_sales': '实际入账金额',
        'total_error': '误差',
        'pos_total': 'POS机总营业额',
        'financial_check_status': '审核状态',
        'create_daily_report': '新建日报',
        'bank_deposit': '银行存款金额(BC)',
        'bank_fee': '存款手续费 (BF)',
        'start_check': '开始核对',
        'back_to_list': '返回列表',
        'report_date': '报告日期',
    },
    'th': {
        'role': 'ตำแหน่ง',
        'store_id': 'สาขา',
        'select_store': 'กรุณาเลือกสาขา',
        'employee_number': 'รหัสพนักงาน',
        'employee_number_placeholder': 'เช่น 91001',
        'employee_number_tip': 'กรุณากรอกรหัสพนักงาน (เช่น: รหัสร้าน+สามหลัก เช่น 91001)',
        'username': 'ชื่อผู้ใช้',
        'password': 'รหัสผ่าน',
        'confirm_password': 'ยืนยันรหัสผ่าน',
        'register_title': 'สมัครสมาชิกใหม่',
        'register_btn': 'สมัครสมาชิก',
        'already_have_account': 'มีบัญชีอยู่แล้ว?',
        'login_now': 'เข้าสู่ระบบทันที',
        'login_title': 'เข้าสู่ระบบ',
        'login_welcome': 'ยินดีต้อนรับกลับมา',
        'login_subtitle': 'กรุณาเข้าสู่ระบบบัญชีของคุณ',
        'remember_me': 'จดจำฉัน',
        'login_btn': 'เข้าสู่ระบบ',
        'no_account': 'ยังไม่มีบัญชี?',
        'register_now': 'สมัครสมาชิก',
        'profile_title': 'ข้อมูลส่วนตัว',
        'profile_subtitle': 'โปรไฟล์ของฉัน',
        'role_admin': 'ผู้ดูแลระบบ',
        'role_finance': 'การเงิน',
        'role_head_manager': 'ผู้จัดการร้าน',
        'role_staff': 'พนักงาน',
        'role_unset': 'ยังไม่ได้ตั้งค่า',
        'unknown': 'ไม่ทราบ',
        'join_year': 'ปีที่เข้าร่วม',
        'related_store': 'สาขาที่เกี่ยวข้อง',
        'profile_completion': 'ความสมบูรณ์ของข้อมูล',
        'completed': 'รายการที่เสร็จสิ้น',
        'quick_actions': 'การดำเนินการด่วน',
        'edit_profile': 'แก้ไขข้อมูล',
        'change_password': 'เปลี่ยนรหัสผ่าน',
        'change_password_tip': 'ฟังก์ชันเปลี่ยนรหัสผ่านอยู่ระหว่างการพัฒนา',
        'basic_info': 'ข้อมูลพื้นฐาน',
        'real_name': 'ชื่อจริง',
        'not_filled': 'ยังไม่ได้กรอก',
        'not_assigned': 'ยังไม่ได้กำหนด',
        'id_card_number': 'หมายเลขบัตรประชาชน',
        'register_time': 'เวลาสมัคร',
        'work_info': 'ข้อมูลการทำงาน',
        'start_date': 'วันที่เริ่มงาน',
        'end_date': 'วันที่ลาออก',
        'on_job': 'ทำงานอยู่',
        'is_primary_contact': 'ผู้ติดต่อหลัก',
        'yes': '✔ ใช่',
        'no': '❌ ไม่ใช่',
        'contact_info': 'ข้อมูลติดต่อ',
        'phone': 'เบอร์โทรศัพท์',
        'email': 'อีเมล',
        'bank_info': 'ข้อมูลธนาคาร',
        'bank_name': 'ชื่อธนาคาร',
        'bank_account_number': 'เลขที่บัญชีธนาคาร',
        'employee_number_admin_only': 'ฟิลด์นี้กำหนดโดยผู้ดูแลระบบ ไม่สามารถแก้ไขเองได้',
        'unassigned': 'ยังไม่ได้กำหนด',
        'edit_profile_subtitle': 'กรุณากรอกข้อมูลส่วนตัวของคุณให้ครบถ้วน',
        'edit_profile_for': 'แก้ไขโปรไฟล์ของ',
        'edit_profile_tip': 'การกรอกข้อมูลส่วนตัวให้ครบถ้วนช่วยเพิ่มความปลอดภัยของบัญชีและอำนวยความสะดวกในการทำงานเป็นทีมและการเบิกจ่ายทางการเงิน',
        'personal_info': 'ข้อมูลส่วนตัว',
        'real_name_placeholder': 'กรุณากรอกชื่อจริง',
        'real_name_required': 'กรุณากรอกชื่อจริง',
        'id_card_number_placeholder': 'กรุณากรอกหมายเลขบัตรประชาชน',
        'phone_placeholder': 'กรุณากรอกเบอร์โทรศัพท์',
        'email_placeholder': 'กรุณากรอกอีเมล',
        'email_invalid': 'กรุณากรอกอีเมลที่ถูกต้อง',
        'line_id_placeholder': 'กรุณากรอก LINE ID',
        'bank_and_job_info': 'ข้อมูลธนาคารและการทำงาน',
        'store_only_notice': 'ส่วนนี้สำหรับพนักงานสาขาเท่านั้น ใช้สำหรับการจ่ายเงินเดือนและการเบิกจ่าย',
        'bank_name_placeholder': 'กรุณากรอกชื่อธนาคาร',
        'bank_account_number_placeholder': 'กรุณากรอกเลขที่บัญชีธนาคาร',
        'save': 'บันทึก',
        'cancel_edit': 'ยกเลิก',
        'tip': 'คำแนะนำ:',
        'profile': 'ข้อมูลส่วนตัว',
        'home': 'หน้าหลัก',
        'sales_manage': 'จัดการยอดขาย',
        'reimbursement': 'เบิกจ่าย',
        'system_manage': 'การจัดการระบบ',
        'user_manage': 'จัดการผู้ใช้',
        'all_reimbursement': 'คำขอเบิกจ่ายทั้งหมด',
        'logout': 'ออกจากระบบ',
        'logout_confirm': 'คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?',
        'user_detail': 'รายละเอียดผู้ใช้',
        'user_detail_subtitle': 'ข้อมูลรายละเอียดผู้ใช้',
        'active': 'ใช้งาน',
        'inactive': 'ปิดใช้งาน',
        'profile_completed': 'ข้อมูลสมบูรณ์',
        'profile_incomplete': 'ข้อมูลไม่สมบูรณ์',
        'created_at': 'เวลาสร้าง',
        'store': 'สาขา',
        'back_to_list': 'กลับไปยังรายการ',
        'edit_user': 'แก้ไขผู้ใช้',
        'reset_password': 'รีเซ็ตรหัสผ่าน',
        'reset_password_confirm': 'คุณแน่ใจหรือไม่ว่าต้องการรีเซ็ตรหัสผ่านของผู้ใช้นี้?',
        'delete_user': 'ลบผู้ใช้',
        'delete_user_confirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบผู้ใช้นี้?',
        'sales_check_title': 'ตรวจสอบข้อมูลการขาย',
        'sales_check_bi': 'BI ตรวจสอบการขาย',
        'report_user': 'ผู้รายงาน',
        'pos_sales_info': 'ข้อมูลการขาย POS',
        'cash_income': 'รายรับเงินสด (C)',
        'pos_income': 'รายรับอิเล็กทรอนิกส์ (P)',
        'voucher_amount': 'จำนวนคูปองที่ใช้ (R)',
        'sales_slip_image': 'สลิป POS',
        'third_party_sales_info': 'ข้อมูลการขายแพลตฟอร์มเดลิเวอรี',
        'takeaway_amount': 'รายรับจากแพลตฟอร์มเดลิเวอรี (T1)',
        'takeaway_platform_receipt': 'สลิปแพลตฟอร์มเดลิเวอรี',
        'actual_sales_info': 'ข้อมูลยอดเงินเข้าจริง',
        'electronic_actual_arrival': 'ยอดเงินเข้าอิเล็กทรอนิกส์ (EA)',
        'electronic_actual_arrival_receipt': 'สลิปยอดเงินเข้าอิเล็กทรอนิกส์',
        'bank_receipt_image': 'สลิปเงินฝากธนาคาร',
        'save_daily_report': 'บันทึกรายงานประจำวัน',
        'save': 'บันทึก',
        'edit': 'แก้ไข',
        'detail': 'รายละเอียด',
        'filter': 'กรอง',
        'approved': 'ตรวจสอบแล้ว',
        'pending': 'รอตรวจสอบ',
        'all_status': 'ทั้งหมด',
        'all_stores': 'ทุกสาขา',
        'finance_remark': 'หมายเหตุฝ่ายการเงิน',
        'finance_remark_placeholder': 'สามารถกรอกหมายเหตุฝ่ายการเงิน',
        'no_remark': 'ไม่มีหมายเหตุ',
        'key_change_history': 'ประวัติการแก้ไขฟิลด์สำคัญ',
        'field': 'ฟิลด์',
        'old_value': 'ค่าเดิม',
        'new_value': 'ค่าใหม่',
        'operator': 'ผู้ดำเนินการ',
        'reason': 'เหตุผล',
        'time': 'เวลา',
        'no_key_change_history': 'ไม่มีประวัติการแก้ไขฟิลด์สำคัญ',
        'daily_voucher': 'สลิปประจำวัน',
        'voucher_img': 'รูปภาพสลิป',
        'pdf_preview': 'ดู PDF',
        'file': 'ไฟล์',
        'no_voucher': 'ไม่มีสลิป',
        'prev_page': 'หน้าก่อน',
        'next_page': 'หน้าถัดไป',
        'page_info': 'หน้า',
        'page': 'หน้า',
        'daily_report': 'รายงานประจำวัน',
        'sales_manage_list_title': 'รายการจัดการยอดขาย',
        'action': 'การดำเนินการ',
        'actual_sales': 'ยอดเงินเข้าจริง',
        'total_error': 'ส่วนต่าง',
        'pos_total': 'ยอดขาย POS รวม',
        'financial_check_status': 'สถานะตรวจสอบ',
        'create_daily_report': 'สร้างรายงานประจำวันใหม่',
        'bank_deposit': 'เงินฝากธนาคาร (BC)',
        'bank_fee': 'ค่าธรรมเนียมฝาก (BF)',
        'start_check': 'เริ่มตรวจสอบ',
        'back_to_list': 'กลับสู่รายการ',
        'report_date': 'วันที่รายงาน',
    }
}
