"""init

Revision ID: 2591ca290b0e
Revises: 
Create Date: 2025-08-27 22:01:48.718247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2591ca290b0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_report_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HEAD_MANAGER', 'FINANCE', 'BRANCH_MANAGER', 'EMPLOYEE', name='roletype'), nullable=False, comment='角色'),
    sa.Column('daily_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_time', sa.String(length=8), nullable=False),
    sa.Column('weekly_time', sa.String(length=8), nullable=False),
    sa.Column('monthly_time', sa.String(length=8), nullable=False),
    sa.Column('weekly_day', sa.String(length=2), nullable=False),
    sa.Column('monthly_day', sa.String(length=2), nullable=False),
    sa.Column('emails', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('email_task_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.Enum('daily', 'weekly', 'monthly', name='emailtasktype'), nullable=False, comment='任务类型'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='数据统计开始时间'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='数据统计结束时间'),
    sa.Column('recipients', sa.Text(), nullable=False, comment='收件人邮箱列表（逗号分隔）'),
    sa.Column('status', sa.Enum('success', 'partial_fail', 'fail', name='emailtaskstatus'), nullable=False, comment='发送结果状态'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='成功发送数量'),
    sa.Column('fail_count', sa.Integer(), nullable=False, comment='失败数量'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.String(length=32), nullable=False, comment='店铺唯一标识符'),
    sa.Column('store_name', sa.String(length=100), nullable=False, comment='店铺名称'),
    sa.Column('store_address', sa.String(length=255), nullable=True, comment='店铺地图地址链接'),
    sa.Column('third_party_platform', sa.Boolean(), nullable=True, comment='是否开启第三方外卖平台'),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('users',
    sa.Column('employee_number', sa.Integer(), nullable=True, comment='员工编号（店铺编号+三位序号）'),
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户主键，自增 ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='登录密码哈希'),
    sa.Column('user_status', sa.Integer(), nullable=False, comment='用户状态（1=活跃，0=禁用）'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='最近一次登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('role', sa.Enum('ADMIN', 'HEAD_MANAGER', 'FINANCE', 'BRANCH_MANAGER', 'EMPLOYEE', name='roletype'), nullable=True, comment='用户角色'),
    sa.Column('store_id', sa.String(length=32), nullable=True, comment='关联店铺ID (门店组用户专属)'),
    sa.Column('real_name', sa.String(length=100), nullable=True, comment='真实姓名'),
    sa.Column('id_card_number', sa.String(length=100), nullable=True, comment='身份证号'),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='银行名称'),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True, comment='银行账号'),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=True, comment='是否为店铺主要联系人'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='联系电话'),
    sa.Column('line_id', sa.String(length=100), nullable=True, comment='LINE ID'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='电子邮箱'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='入职日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='离职日期'),
    sa.Column('profile_completed', sa.Boolean(), nullable=True, comment='员工档案是否已完善（仅能一次性填写）'),
    sa.Column('id_card_copy', sa.String(length=255), nullable=True, comment='身份证复印件文件路径（受控访问，避免隐私泄露）'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_sales',
    sa.Column('theoretical_total', sa.Float(), nullable=True, comment='理论营收(T2)=店铺理论营业额(T0)+第三方外卖平台收入(T1)-POS机小票里显示的代金券总金额-银行存款金额'),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='日报主键'),
    sa.Column('store_id', sa.String(length=32), nullable=False, comment='门店ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上报人ID'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='营业日期'),
    sa.Column('cash_income', sa.Float(), nullable=True, comment='现金收入 (C)'),
    sa.Column('pos_income', sa.Float(), nullable=True, comment='电子支付收入 (P)'),
    sa.Column('day_pass_income', sa.Float(), nullable=True, comment='外卖收入 (D)'),
    sa.Column('voucher_amount', sa.Float(), nullable=True, comment='代金券使用金额 (R)'),
    sa.Column('pos_total', sa.Float(), nullable=True, comment='店铺理论营业额 (T0) = 现金收入 + 电子支付收入 + 外卖收入 + 代金券使用金额'),
    sa.Column('electronic_actual_arrival', sa.Float(), nullable=True, comment='电子支付实际入账金额 (EA)'),
    sa.Column('bank_deposit', sa.Float(), nullable=True, comment='银行存款金额 (BC)'),
    sa.Column('bank_fee', sa.Float(), nullable=True, comment='银行存款手续费 (BF)'),
    sa.Column('takeaway_amount', sa.Float(), nullable=False, comment='第三方外卖平台收入 (T1)'),
    sa.Column('actual_sales', sa.Float(), nullable=True, comment='实际总营业额(S)=第三方外卖平台收入(T1)+外卖收入+电子支付实际入账金额+银行存款金额'),
    sa.Column('total_error', sa.Float(), nullable=True, comment='总误差(E)=电子支付实际入账金额+银行存款金额+银行存款手续费-POS机小票里显示的电子支付总金额-POS机小票里显示的现金总金额'),
    sa.Column('cash_difference', sa.Float(), nullable=False, comment='POS现金收入误差(A)，仅存储，默认0'),
    sa.Column('electronic_difference', sa.Float(), nullable=False, comment='POS电子支付误差(B)，仅存储，默认0'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='审核备注'),
    sa.Column('pos_info_completed', sa.Boolean(), nullable=False, comment='第一步(POS)是否完成'),
    sa.Column('takeaway_info_completed', sa.Boolean(), nullable=False, comment='第二步(外卖)是否完成'),
    sa.Column('actual_arrival_info_completed', sa.Boolean(), nullable=False, comment='实际入账金额录入是否完成'),
    sa.Column('is_submitted', sa.Boolean(), nullable=False, comment='是否已最终提交给财务'),
    sa.Column('financial_check_status', sa.Enum('PENDING', 'APPROVED', name='financialcheckstatus'), nullable=False, comment='财务核对状态（仅PENDING/APPROVED）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sales_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_sales_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_sales_user_id'), ['user_id'], unique=False)

    op.create_table('reimbursement_default_cc_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='默认抄送人用户ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uk_default_cc_user')
    )
    op.create_table('reimbursement_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False, comment='报销申请ID'),
    sa.Column('submitter_id', sa.Integer(), nullable=False, comment='申请人ID'),
    sa.Column('store_id', sa.String(length=32), nullable=True, comment='关联店铺ID'),
    sa.Column('primary_category', sa.Enum('SHARED_COST', 'STORE_COST', name='reimbursementprimarycategory'), nullable=False, comment='一级分类'),
    sa.Column('secondary_category', sa.Enum('SHARED_REIMBURSEMENT', 'AGENCY_ACCOUNTING', 'TAXES', 'EMPLOYEE_SOCIAL_SECURITY', 'STORE_MANAGEMENT', 'OTHER_SHARED_COST', 'MIXTURE_MATERIAL', 'MATERIAL_TRANSPORT', 'FIXED_SALARY', 'TEMPORARY_SALARY', 'EXTERNAL_LEMON', 'STORE_PETTY_CASH', 'RENTAL_TAX', 'UTILITIES', 'STORE_RENT', 'WAREHOUSE_RENT', 'OTHER_COST', name='reimbursementsecondarycategory'), nullable=False, comment='二级分类'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='报销金额'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='货币单位'),
    sa.Column('description', sa.Text(), nullable=True, comment='报销说明'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DRAFT', name='reimbursementstatus'), nullable=False, comment='审批状态'),
    sa.Column('check_status', sa.Enum('CHECKED', 'UNCHECKED', name='reimbursementcheckstatus'), nullable=False, comment='核对状态'),
    sa.Column('approval_comments', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批通过时间'),
    sa.Column('approver_id', sa.Integer(), nullable=False, comment='审批人ID'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('bank_deposit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='日报ID'),
    sa.Column('field_name', sa.String(length=64), nullable=False, comment='字段名'),
    sa.Column('old_value', sa.Float(), nullable=True, comment='原值'),
    sa.Column('new_value', sa.Float(), nullable=False, comment='新值'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('operator_role', sa.String(length=32), nullable=True, comment='操作人角色'),
    sa.Column('remark', sa.String(length=255), nullable=False, comment='变更理由'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_sales.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_deposit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_deposit_history_report_id'), ['report_id'], unique=False)

    op.create_table('daily_sales_attachments',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False, comment='凭证ID'),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='日报ID'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='文件路径（本地磁盘，含user_id/store_id/report_date）'),
    sa.Column('attachment_type', sa.Enum('sales_slip', 'bank_receipt', 'takeaway_screenshot', 'electronic_actual_arrival_receipt', 'image', 'pdf', name='attachmenttype'), nullable=False, comment='附件类型（小票/银行/外卖/图片/PDF等）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['report_id'], ['daily_sales.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('reimbursement_attachments',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False, comment='附件ID'),
    sa.Column('request_id', sa.Integer(), nullable=False, comment='所属报销申请ID'),
    sa.Column('attachment_type', sa.Enum('SUBMISSION', 'APPROVAL', name='reimbursementattachmenttype'), nullable=False, comment='附件类型（提交/审批）'),
    sa.Column('uploader_id', sa.Integer(), nullable=False, comment='上传人ID'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='文件存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='文件MIME类型'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.ForeignKeyConstraint(['request_id'], ['reimbursement_requests.request_id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('reimbursement_cc_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='抄送记录ID'),
    sa.Column('request_id', sa.Integer(), nullable=False, comment='报销申请ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='抄送人用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['request_id'], ['reimbursement_requests.request_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'user_id', name='uk_request_user_cc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reimbursement_cc_recipients')
    op.drop_table('reimbursement_attachments')
    op.drop_table('daily_sales_attachments')
    with op.batch_alter_table('bank_deposit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_deposit_history_report_id'))

    op.drop_table('bank_deposit_history')
    op.drop_table('reimbursement_requests')
    op.drop_table('reimbursement_default_cc_recipients')
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_sales_store_id'))
        batch_op.drop_index(batch_op.f('ix_daily_sales_report_date'))

    op.drop_table('daily_sales')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('email_task_log')
    op.drop_table('email_report_config')
    # ### end Alembic commands ###
