"""add total_value_thb to mx_stocktake_header

Revision ID: 454871eb1a85
Revises: d4e5f6a7b8c9
Create Date: 2026-02-06 21:41:45.533404

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '454871eb1a85'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('mx_stocktake_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value_thb', sa.Numeric(precision=12, scale=2), nullable=True,
                                      comment='库存总价值（泰铢），提交时计算'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mx_stocktake_header', schema=None) as batch_op:
        batch_op.drop_column('total_value_thb')

    # ### end Alembic commands ###
