"""check_pending_changes

Revision ID: 63219086f39d
Revises: 454871eb1a85
Create Date: 2026-02-07 13:09:48.977328

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63219086f39d'
down_revision = '454871eb1a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mx_inventory_check', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mx_inv_header'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_mx_inv_header_id'))
        batch_op.drop_index(batch_op.f('ix_mx_inv_material_code'))
        batch_op.drop_index(batch_op.f('ix_mx_inv_store_date'))
        batch_op.drop_index(batch_op.f('ix_mx_inv_valid_until'))
        batch_op.create_index(batch_op.f('ix_mx_inventory_check_check_date'), ['check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_check_header_id'), ['header_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_check_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_check_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_check_valid_until'), ['valid_until'], unique=False)
        batch_op.create_foreign_key(None, 'mx_stocktake_header', ['header_id'], ['id'])

    with op.batch_alter_table('mx_inventory_draft', schema=None) as batch_op:
        batch_op.alter_column('store_id',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
                              comment='店铺ID',
                              existing_nullable=False)
        batch_op.alter_column('check_date',
                              existing_type=sa.DATE(),
                              comment='最后保存草稿时选择的盘点日期',
                              existing_nullable=False)
        batch_op.alter_column('material_code',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment='物料编码',
                              existing_nullable=False)
        batch_op.alter_column('material_name',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment='物料名称（冗余，便于展示）',
                              existing_nullable=False)
        batch_op.alter_column('spec_model',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment='规格（冗余，便于展示）',
                              existing_nullable=True)
        batch_op.alter_column('remaining_case_qty',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment='剩余整件数',
                              existing_nullable=False,
                              existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remaining_group_qty',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment='剩余散件数',
                              existing_nullable=False,
                              existing_server_default=sa.text("'0'"))
        batch_op.alter_column('valid_until',
                              existing_type=sa.DATE(),
                              comment='有效期至',
                              existing_nullable=True)
        batch_op.alter_column('operator',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment='操作员(username)',
                              existing_nullable=True)
        batch_op.alter_column('operated_at',
                              existing_type=mysql.DATETIME(),
                              comment='操作时间',
                              existing_nullable=False)
        batch_op.alter_column('header_id',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment='关联盘点单头',
                              existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_mx_draft_header'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_mx_draft_header_id'))
        batch_op.drop_index(batch_op.f('ix_mx_draft_material_code'))
        batch_op.drop_index(batch_op.f('ix_mx_draft_store'))
        batch_op.drop_index(batch_op.f('ix_mx_draft_store_date'))
        batch_op.drop_index(batch_op.f('ix_mx_draft_valid_until'))
        batch_op.create_index(batch_op.f('ix_mx_inventory_draft_check_date'), ['check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_draft_header_id'), ['header_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_draft_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_draft_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inventory_draft_valid_until'), ['valid_until'], unique=False)
        batch_op.create_foreign_key(None, 'mx_stocktake_header', ['header_id'], ['id'])

    with op.batch_alter_table('mx_material_info', schema=None) as batch_op:
        batch_op.alter_column('material_code',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment='物料编码',
                              existing_nullable=False)
        batch_op.alter_column('cn_name',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment='中文名称',
                              existing_nullable=False)
        batch_op.alter_column('th_name',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment='泰文名称',
                              existing_nullable=True)
        batch_op.alter_column('spec_model',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment='规格型号',
                              existing_nullable=False)
        batch_op.alter_column('per_group_qty',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment='每组数量',
                              existing_nullable=False)
        batch_op.alter_column('price_per_case',
                              existing_type=mysql.DECIMAL(precision=12, scale=2),
                              comment='每件单价（泰铢）',
                              existing_nullable=True)
        batch_op.alter_column('price_per_group',
                              existing_type=mysql.DECIMAL(precision=12, scale=2),
                              comment='每组单价（泰铢）',
                              existing_nullable=True)
        batch_op.alter_column('category',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
                              comment='物料类别',
                              existing_nullable=False)
        batch_op.alter_column('safety_stock',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment='安全库存',
                              existing_nullable=True)
        batch_op.alter_column('status',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
                              comment='状态：启用/禁用',
                              existing_nullable=False,
                              existing_server_default=sa.text("'启用'"))
        batch_op.alter_column('product_image',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment='预留产品图片字段（文本路径/标识）',
                              existing_nullable=True)
        batch_op.alter_column('remark',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment='备注',
                              existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_mx_material_category'))
        batch_op.drop_index(batch_op.f('ix_mx_material_code'))
        batch_op.drop_index(batch_op.f('uq_mx_material_code'))
        batch_op.create_index(batch_op.f('ix_mx_material_info_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_material_info_material_code'), ['material_code'], unique=True)

    with op.batch_alter_table('mx_stocktake_header', schema=None) as batch_op:
        batch_op.alter_column('store_id',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
                              comment='店铺ID',
                              existing_nullable=False)
        batch_op.alter_column('check_date',
                              existing_type=sa.DATE(),
                              comment='盘点日期',
                              existing_nullable=False)
        batch_op.alter_column('status',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
                              comment='状态：DRAFT/COMMITTED',
                              existing_nullable=False,
                              existing_server_default=sa.text("'DRAFT'"))
        batch_op.alter_column('created_by',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment='创建人(username)',
                              existing_nullable=True)
        batch_op.alter_column('committed_by',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment='提交人(username)',
                              existing_nullable=True)
        batch_op.alter_column('committed_at',
                              existing_type=mysql.DATETIME(),
                              comment='提交时间',
                              existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_mx_stocktake_store_date'))
        batch_op.create_index(batch_op.f('ix_mx_stocktake_header_check_date'), ['check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_stocktake_header_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mx_stocktake_header', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mx_stocktake_header_store_id'))
        batch_op.drop_index(batch_op.f('ix_mx_stocktake_header_check_date'))
        batch_op.create_index(batch_op.f('ix_mx_stocktake_store_date'), ['store_id', 'check_date'], unique=False)
        batch_op.alter_column('committed_at',
                              existing_type=mysql.DATETIME(),
                              comment=None,
                              existing_comment='提交时间',
                              existing_nullable=True)
        batch_op.alter_column('committed_by',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment=None,
                              existing_comment='提交人(username)',
                              existing_nullable=True)
        batch_op.alter_column('created_by',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment=None,
                              existing_comment='创建人(username)',
                              existing_nullable=True)
        batch_op.alter_column('status',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
                              comment=None,
                              existing_comment='状态：DRAFT/COMMITTED',
                              existing_nullable=False,
                              existing_server_default=sa.text("'DRAFT'"))
        batch_op.alter_column('check_date',
                              existing_type=sa.DATE(),
                              comment=None,
                              existing_comment='盘点日期',
                              existing_nullable=False)
        batch_op.alter_column('store_id',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
                              comment=None,
                              existing_comment='店铺ID',
                              existing_nullable=False)

    with op.batch_alter_table('mx_material_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mx_material_info_material_code'))
        batch_op.drop_index(batch_op.f('ix_mx_material_info_category'))
        batch_op.create_index(batch_op.f('uq_mx_material_code'), ['material_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_mx_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_material_category'), ['category'], unique=False)
        batch_op.alter_column('remark',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment=None,
                              existing_comment='备注',
                              existing_nullable=True)
        batch_op.alter_column('product_image',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment=None,
                              existing_comment='预留产品图片字段（文本路径/标识）',
                              existing_nullable=True)
        batch_op.alter_column('status',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
                              comment=None,
                              existing_comment='状态：启用/禁用',
                              existing_nullable=False,
                              existing_server_default=sa.text("'启用'"))
        batch_op.alter_column('safety_stock',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment=None,
                              existing_comment='安全库存',
                              existing_nullable=True)
        batch_op.alter_column('category',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
                              comment=None,
                              existing_comment='物料类别',
                              existing_nullable=False)
        batch_op.alter_column('price_per_group',
                              existing_type=mysql.DECIMAL(precision=12, scale=2),
                              comment=None,
                              existing_comment='每组单价（泰铢）',
                              existing_nullable=True)
        batch_op.alter_column('price_per_case',
                              existing_type=mysql.DECIMAL(precision=12, scale=2),
                              comment=None,
                              existing_comment='每件单价（泰铢）',
                              existing_nullable=True)
        batch_op.alter_column('per_group_qty',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment=None,
                              existing_comment='每组数量',
                              existing_nullable=False)
        batch_op.alter_column('spec_model',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment=None,
                              existing_comment='规格型号',
                              existing_nullable=False)
        batch_op.alter_column('th_name',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment=None,
                              existing_comment='泰文名称',
                              existing_nullable=True)
        batch_op.alter_column('cn_name',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment=None,
                              existing_comment='中文名称',
                              existing_nullable=False)
        batch_op.alter_column('material_code',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment=None,
                              existing_comment='物料编码',
                              existing_nullable=False)

    with op.batch_alter_table('mx_inventory_draft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_mx_draft_header'), 'mx_stocktake_header', ['header_id'], ['id'],
                                    ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_mx_inventory_draft_valid_until'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_draft_store_id'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_draft_material_code'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_draft_header_id'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_draft_check_date'))
        batch_op.create_index(batch_op.f('ix_mx_draft_valid_until'), ['valid_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_draft_store_date'), ['store_id', 'check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_draft_store'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_draft_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_draft_header_id'), ['header_id'], unique=False)
        batch_op.alter_column('header_id',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment=None,
                              existing_comment='关联盘点单头',
                              existing_nullable=True)
        batch_op.alter_column('operated_at',
                              existing_type=mysql.DATETIME(),
                              comment=None,
                              existing_comment='操作时间',
                              existing_nullable=False)
        batch_op.alter_column('operator',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment=None,
                              existing_comment='操作员(username)',
                              existing_nullable=True)
        batch_op.alter_column('valid_until',
                              existing_type=sa.DATE(),
                              comment=None,
                              existing_comment='有效期至',
                              existing_nullable=True)
        batch_op.alter_column('remaining_group_qty',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment=None,
                              existing_comment='剩余散件数',
                              existing_nullable=False,
                              existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remaining_case_qty',
                              existing_type=mysql.INTEGER(display_width=11),
                              comment=None,
                              existing_comment='剩余整件数',
                              existing_nullable=False,
                              existing_server_default=sa.text("'0'"))
        batch_op.alter_column('spec_model',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment=None,
                              existing_comment='规格（冗余，便于展示）',
                              existing_nullable=True)
        batch_op.alter_column('material_name',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
                              comment=None,
                              existing_comment='物料名称（冗余，便于展示）',
                              existing_nullable=False)
        batch_op.alter_column('material_code',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
                              comment=None,
                              existing_comment='物料编码',
                              existing_nullable=False)
        batch_op.alter_column('check_date',
                              existing_type=sa.DATE(),
                              comment=None,
                              existing_comment='最后保存草稿时选择的盘点日期',
                              existing_nullable=False)
        batch_op.alter_column('store_id',
                              existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
                              comment=None,
                              existing_comment='店铺ID',
                              existing_nullable=False)

    with op.batch_alter_table('mx_inventory_check', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_mx_inv_header'), 'mx_stocktake_header', ['header_id'], ['id'],
                                    ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_mx_inventory_check_valid_until'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_check_store_id'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_check_material_code'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_check_header_id'))
        batch_op.drop_index(batch_op.f('ix_mx_inventory_check_check_date'))
        batch_op.create_index(batch_op.f('ix_mx_inv_valid_until'), ['valid_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inv_store_date'), ['store_id', 'check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inv_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mx_inv_header_id'), ['header_id'], unique=False)

    # ### end Alembic commands ###
