"""更新表结构

Revision ID: 7b4517cb3530
Revises: bbf3c1cae35a
Create Date: 2025-09-13 18:45:27.493519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4517cb3530'
down_revision = 'bbf3c1cae35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_tasks',
    sa.Column('id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('notification_type', sa.Enum('RENOVATION_TASK_ASSIGNED', 'RENOVATION_OVERDUE_WARNING', 'RENOVATION_VERIFICATION_NEEDED', 'RENOVATION_VERIFICATION_RESULT', 'REIMBURSEMENT_NOTIFICATION', 'ATTENDANCE_NOTIFICATION', 'SYSTEM_NOTIFICATION', name='notificationtype'), nullable=False, comment='通知类型'),
    sa.Column('related_object_id', sa.String(length=100), nullable=True, comment='关联对象ID'),
    sa.Column('module_name', sa.String(length=50), nullable=False, comment='关联模块'),
    sa.Column('receivers', sa.Text(), nullable=True, comment='接收人列表（JSON格式）'),
    sa.Column('channels', sa.String(length=255), nullable=True, comment='发送渠道'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRY', name='notificationstatus'), nullable=True, comment='发送状态'),
    sa.Column('send_time', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False, comment='模板ID'),
    sa.Column('notification_type', sa.Enum('RENOVATION_TASK_ASSIGNED', 'RENOVATION_OVERDUE_WARNING', 'RENOVATION_VERIFICATION_NEEDED', 'RENOVATION_VERIFICATION_RESULT', 'REIMBURSEMENT_NOTIFICATION', 'ATTENDANCE_NOTIFICATION', 'SYSTEM_NOTIFICATION', name='notificationtype'), nullable=False, comment='通知类型'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言（zh/th）'),
    sa.Column('title_template', sa.String(length=255), nullable=True, comment='标题模板'),
    sa.Column('content_template', sa.Text(), nullable=True, comment='内容模板'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), nullable=False, comment='配置ID'),
    sa.Column('notification_type', sa.Enum('RENOVATION_TASK_ASSIGNED', 'RENOVATION_OVERDUE_WARNING', 'RENOVATION_VERIFICATION_NEEDED', 'RENOVATION_VERIFICATION_RESULT', 'REIMBURSEMENT_NOTIFICATION', 'ATTENDANCE_NOTIFICATION', 'SYSTEM_NOTIFICATION', name='notificationtype'), nullable=False, comment='通知类型'),
    sa.Column('module_name', sa.String(length=50), nullable=False, comment='模块名称'),
    sa.Column('receiver_rules', sa.Text(), nullable=True, comment='接收人规则（JSON格式）'),
    sa.Column('channels', sa.String(length=255), nullable=True, comment='发送渠道（逗号分隔）'),
    sa.Column('template_id', sa.Integer(), nullable=True, comment='通知模板ID'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='启用状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_config')
    op.drop_table('notification_templates')
    op.drop_table('notification_tasks')
    # ### end Alembic commands ###
