"""创建数据库

Revision ID: 8e4f1cd2eb18
Revises: 
Create Date: 2025-06-19 15:08:35.016370

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8e4f1cd2eb18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('store_id', sa.String(length=32), nullable=False, comment='店铺唯一标识符'),
    sa.Column('store_name', sa.String(length=100), nullable=False, comment='店铺名称'),
    sa.Column('store_address', sa.String(length=255), nullable=True, comment='店铺地图地址链接'),
    sa.Column('third_party_platform', sa.Boolean(), nullable=True, comment='是否开启第三方外卖平台'),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户主键，自增 ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='登录密码哈希'),
    sa.Column('user_status', sa.Integer(), nullable=False, comment='用户状态（1=活跃，0=禁用）'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='最近一次登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('role', sa.Enum('ADMIN', 'HEAD_MANAGER', 'FINANCE', 'BRANCH_MANAGER', 'EMPLOYEE', name='roletype'), nullable=True, comment='用户角色 (admin, head_manager, finance, branch_manager, employee)'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_sales',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False, comment='报表ID'),
    sa.Column('store_id', sa.String(length=32), nullable=False, comment='店铺ID'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='报表日期'),
    sa.Column('total_income', sa.Numeric(precision=18, scale=2), nullable=True, comment='POS机小票总收入 (T)'),
    sa.Column('cash_sales', sa.Numeric(precision=18, scale=2), nullable=True, comment='现金收入 (C)'),
    sa.Column('electronic_sales', sa.Numeric(precision=18, scale=2), nullable=True, comment='电子支付收入 (P)'),
    sa.Column('system_takeaway_sales', sa.Numeric(precision=18, scale=2), nullable=True, comment='POS机外卖收入 (D)'),
    sa.Column('takeaway_platform_sales', sa.Numeric(precision=18, scale=2), nullable=True, comment='第三方外卖平台收入 (Q2)'),
    sa.Column('cash_difference', sa.Numeric(precision=18, scale=2), nullable=True, comment='现金误差 (A)'),
    sa.Column('electronic_difference', sa.Numeric(precision=18, scale=2), nullable=True, comment='电子支付误差 (B)'),
    sa.Column('voucher_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='代金券使用金额 (R)'),
    sa.Column('bank_fee', sa.Numeric(precision=18, scale=2), nullable=True, comment='银行手续费 (F)'),
    sa.Column('bank_deposit', sa.Numeric(precision=18, scale=2), nullable=True, comment='实际到账金额'),
    sa.Column('actual_sales', sa.Numeric(precision=18, scale=2), nullable=True, comment='店铺实际营业额'),
    sa.Column('report_status', sa.Enum('DRAFT_POS', 'DRAFT_TAKEAWAY', 'DRAFT_BANK', 'COMPLETED_INFO', 'COMPLETED_BANK', 'COMPLETED_TAKEEAWAY', 'SUBMITTED', name='reportstatus'), nullable=True, comment='上报状态'),
    sa.Column('financial_check_status', sa.Enum('PENDING', 'BANK_RECEIVED', 'TAKEEAWAY_RECEIVED', 'AMOUNT_VERIFIED', 'REQUIRES_REMEDIATION', 'CHECKED', name='financialcheckstatus'), nullable=True, comment='财务核对状态'),
    sa.Column('archived', sa.Boolean(), nullable=True, comment='是否已归档'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='最后修改人'),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='修改时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('store_staff',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False, comment='员工主键'),
    sa.Column('store_id', sa.String(length=32), nullable=False, comment='所属店铺 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('bank_account_name', sa.String(length=64), nullable=False, comment='开户行名称'),
    sa.Column('bank_account_number', sa.String(length=64), nullable=False, comment='银行卡号'),
    sa.Column('staff_position', sa.String(length=50), nullable=False, comment='职位'),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=True, comment='是否主联系人'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='电话'),
    sa.Column('line_id', sa.String(length=64), nullable=True, comment='Line账号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱地址'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='入职日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='离职日期'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('daily_sales_attachments',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False, comment='凭证ID'),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='日报ID'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='文件路径'),
    sa.Column('attachment_type', sa.Enum('sales_slip', 'bank_receipt', 'takeaway_screenshot', 'image', 'pdf', name='attachmenttype'), nullable=False, comment='附件类型'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['report_id'], ['daily_sales.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_sales_attachments')
    op.drop_table('store_staff')
    op.drop_table('daily_sales')
    op.drop_table('users')
    op.drop_table('stores')
    # ### end Alembic commands ###
