"""init

Revision ID: 9f673d59a005
Revises: 
Create Date: 2025-08-04 13:15:10.687508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f673d59a005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reimbursement_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False, comment='报销申请ID'),
    sa.Column('submitter_id', sa.Integer(), nullable=False, comment='申请人ID'),
    sa.Column('store_id', sa.String(length=32), nullable=True, comment='关联店铺ID'),
    sa.Column('primary_category', sa.Enum('SHARED_COST', 'STORE_COST', name='reimbursementprimarycategory'), nullable=False, comment='一级分类'),
    sa.Column('secondary_category', sa.Enum('SHARED_REIMBURSEMENT', 'AGENCY_ACCOUNTING', 'TAXES', 'EMPLOYEE_SOCIAL_SECURITY', 'STORE_MANAGEMENT', 'OTHER_SHARED_COST', 'MIXTURE_MATERIAL', 'MATERIAL_TRANSPORT', 'FIXED_SALARY', 'TEMPORARY_SALARY', 'EXTERNAL_LEMON', 'STORE_PETTY_CASH', 'RENTAL_TAX', 'UTILITIES', 'STORE_RENT', 'WAREHOUSE_RENT', 'OTHER_COST', name='reimbursementsecondarycategory'), nullable=False, comment='二级分类'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='报销金额'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='货币单位'),
    sa.Column('description', sa.Text(), nullable=True, comment='报销说明'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DRAFT', name='reimbursementstatus'), nullable=False, comment='审批状态'),
    sa.Column('approval_comments', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批通过时间'),
    sa.Column('approver_id', sa.Integer(), nullable=False, comment='审批人ID'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('bank_deposit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='日报ID'),
    sa.Column('field_name', sa.String(length=64), nullable=False, comment='字段名'),
    sa.Column('old_value', sa.Float(), nullable=True, comment='原值'),
    sa.Column('new_value', sa.Float(), nullable=False, comment='新值'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('operator_role', sa.String(length=32), nullable=True, comment='操作人角色'),
    sa.Column('remark', sa.String(length=255), nullable=False, comment='变更理由'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_sales.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_deposit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_deposit_history_report_id'), ['report_id'], unique=False)

    op.create_table('reimbursement_attachments',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False, comment='附件ID'),
    sa.Column('request_id', sa.Integer(), nullable=False, comment='所属报销申请ID'),
    sa.Column('attachment_type', sa.Enum('SUBMISSION', 'APPROVAL', name='reimbursementattachmenttype'), nullable=False, comment='附件类型（提交/审批）'),
    sa.Column('uploader_id', sa.Integer(), nullable=False, comment='上传人ID'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='文件存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='文件MIME类型'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.ForeignKeyConstraint(['request_id'], ['reimbursement_requests.request_id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theoretical_total', sa.Float(), nullable=True, comment='理论营收(T2)=店铺理论营业额(T0)+第三方外卖平台收入(T1)-POS机小票里显示的代金券总金额-银行存款金额'))
        batch_op.add_column(sa.Column('electronic_actual_arrival', sa.Float(), nullable=True, comment='电子支付实际入账金额 (EA)'))
        batch_op.add_column(sa.Column('total_error', sa.Float(), nullable=True, comment='总误差(E)=电子支付实际入账金额+银行存款金额+银行存款手续费-POS机小票里显示的电子支付总金额-POS机小票里显示的现金总金额'))
        batch_op.add_column(sa.Column('cash_difference', sa.Float(), nullable=False, comment='POS现金收入误差(A)，仅存储，默认0'))
        batch_op.add_column(sa.Column('electronic_difference', sa.Float(), nullable=False, comment='POS电子支付误差(B)，仅存储，默认0'))
        batch_op.add_column(sa.Column('actual_arrival_info_completed', sa.Boolean(), nullable=False, comment='实际入账金额录入是否完成'))
        batch_op.alter_column('cash_income',
               existing_type=mysql.FLOAT(),
               comment='现金收入 (C)',
               existing_comment='POS现金收入(C)',
               existing_nullable=True)
        batch_op.alter_column('pos_income',
               existing_type=mysql.FLOAT(),
               comment='电子支付收入 (P)',
               existing_comment='POS电子支付收入(P)',
               existing_nullable=True)
        batch_op.alter_column('day_pass_income',
               existing_type=mysql.FLOAT(),
               comment='外卖收入 (D)',
               existing_comment='POS系统中记录的外卖收入(D)',
               existing_nullable=True)
        batch_op.alter_column('voucher_amount',
               existing_type=mysql.FLOAT(),
               comment='代金券使用金额 (R)',
               existing_comment='财务填写的代金券金额',
               existing_nullable=True)
        batch_op.alter_column('pos_total',
               existing_type=mysql.FLOAT(),
               comment='店铺理论营业额 (T0) = 现金收入 + 电子支付收入 + 外卖收入 + 代金券使用金额',
               existing_comment='POS机小票总收入(T)，=现金+电子支付+POS外卖',
               existing_nullable=True)
        batch_op.alter_column('bank_deposit',
               existing_type=mysql.FLOAT(),
               comment='银行存款金额 (BC)',
               existing_comment='财务填写的实际到账金额',
               existing_nullable=True)
        batch_op.alter_column('bank_fee',
               existing_type=mysql.FLOAT(),
               comment='银行存款手续费 (BF)',
               existing_comment='银行存款手续费',
               existing_nullable=True)
        batch_op.alter_column('takeaway_amount',
               existing_type=mysql.FLOAT(),
               nullable=False,
               comment='第三方外卖平台收入 (T1)',
               existing_comment='第三方外卖平台收入')
        batch_op.alter_column('actual_sales',
               existing_type=mysql.FLOAT(),
               comment='实际总营业额(S)=第三方外卖平台收入(T1)+外卖收入+电子支付实际入账金额+银行存款金额',
               existing_comment='店铺实际营业额（财务核对后）',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='审核备注',
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('financial_check_status',
               existing_type=mysql.ENUM('PENDING', 'BANK_RECEIVED', 'TAKEEAWAY_RECEIVED', 'AMOUNT_VERIFIED', 'REQUIRES_REMEDIATION', 'CHECKED', collation='utf8mb4_unicode_ci'),
               comment='财务核对状态（仅PENDING/APPROVED）',
               existing_comment='财务核对状态',
               existing_nullable=False)
        batch_op.drop_column('bank_info_completed')
        batch_op.drop_column('bank_receipt_amount')
        batch_op.drop_column('archived')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', sa.Integer(), nullable=True, comment='员工编号（店铺编号+三位序号）'))
        batch_op.add_column(sa.Column('id_card_copy', sa.String(length=255), nullable=True, comment='身份证复印件文件路径（受控访问，避免隐私泄露）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('id_card_copy')
        batch_op.drop_column('employee_number')

    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已归档'))
        batch_op.add_column(sa.Column('bank_receipt_amount', mysql.FLOAT(), nullable=True, comment='银行存入的现金金额'))
        batch_op.add_column(sa.Column('bank_info_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='第三步(银行)是否完成'))
        batch_op.alter_column('financial_check_status',
               existing_type=mysql.ENUM('PENDING', 'BANK_RECEIVED', 'TAKEEAWAY_RECEIVED', 'AMOUNT_VERIFIED', 'REQUIRES_REMEDIATION', 'CHECKED', collation='utf8mb4_unicode_ci'),
               comment='财务核对状态',
               existing_comment='财务核对状态（仅PENDING/APPROVED）',
               existing_nullable=False)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='备注',
               existing_comment='审核备注',
               existing_nullable=True)
        batch_op.alter_column('actual_sales',
               existing_type=mysql.FLOAT(),
               comment='店铺实际营业额（财务核对后）',
               existing_comment='实际总营业额(S)=第三方外卖平台收入(T1)+外卖收入+电子支付实际入账金额+银行存款金额',
               existing_nullable=True)
        batch_op.alter_column('takeaway_amount',
               existing_type=mysql.FLOAT(),
               nullable=True,
               comment='第三方外卖平台收入',
               existing_comment='第三方外卖平台收入 (T1)')
        batch_op.alter_column('bank_fee',
               existing_type=mysql.FLOAT(),
               comment='银行存款手续费',
               existing_comment='银行存款手续费 (BF)',
               existing_nullable=True)
        batch_op.alter_column('bank_deposit',
               existing_type=mysql.FLOAT(),
               comment='财务填写的实际到账金额',
               existing_comment='银行存款金额 (BC)',
               existing_nullable=True)
        batch_op.alter_column('pos_total',
               existing_type=mysql.FLOAT(),
               comment='POS机小票总收入(T)，=现金+电子支付+POS外卖',
               existing_comment='店铺理论营业额 (T0) = 现金收入 + 电子支付收入 + 外卖收入 + 代金券使用金额',
               existing_nullable=True)
        batch_op.alter_column('voucher_amount',
               existing_type=mysql.FLOAT(),
               comment='财务填写的代金券金额',
               existing_comment='代金券使用金额 (R)',
               existing_nullable=True)
        batch_op.alter_column('day_pass_income',
               existing_type=mysql.FLOAT(),
               comment='POS系统中记录的外卖收入(D)',
               existing_comment='外卖收入 (D)',
               existing_nullable=True)
        batch_op.alter_column('pos_income',
               existing_type=mysql.FLOAT(),
               comment='POS电子支付收入(P)',
               existing_comment='电子支付收入 (P)',
               existing_nullable=True)
        batch_op.alter_column('cash_income',
               existing_type=mysql.FLOAT(),
               comment='POS现金收入(C)',
               existing_comment='现金收入 (C)',
               existing_nullable=True)
        batch_op.drop_column('actual_arrival_info_completed')
        batch_op.drop_column('electronic_difference')
        batch_op.drop_column('cash_difference')
        batch_op.drop_column('total_error')
        batch_op.drop_column('electronic_actual_arrival')
        batch_op.drop_column('theoretical_total')

    op.drop_table('reimbursement_attachments')
    with op.batch_alter_table('bank_deposit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_deposit_history_report_id'))

    op.drop_table('bank_deposit_history')
    op.drop_table('reimbursement_requests')
    # ### end Alembic commands ###
