"""create testaaa

Revision ID: a3a6c98e7268
Revises: 9128c17d5ad2
Create Date: 2025-08-31 11:05:29.566425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a6c98e7268'
down_revision = '9128c17d5ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testaaa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('value', sa.Float(), nullable=True, comment='数值，可选'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testaaa')
    # ### end Alembic commands ###
