"""增加了店铺整改模块

Revision ID: bbf3c1cae35a
Revises: 5e6f7a8b9c0d
Create Date: 2025-09-02 18:08:58.875543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf3c1cae35a'
down_revision = '5e6f7a8b9c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renovation_categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='分类ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['renovation_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renovation_tasks',
    sa.Column('id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='问题描述'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='renovationtaskpriority'), nullable=True, comment='优先级'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'AWAITING_VERIFICATION', 'COMPLETED', 'CLOSED', 'REJECTED', name='renovationtaskstatus'), nullable=True, comment='任务状态'),
    sa.Column('store_id', sa.String(length=32), nullable=False, comment='责任店铺ID'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人ID'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='负责人ID（店长）'),
    sa.Column('verifier_id', sa.Integer(), nullable=True, comment='验收人ID（默认总店长）'),
    sa.Column('due_date', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始处理时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验收时间'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='关闭时间'),
    sa.Column('verification_result', sa.Enum('PASSED', 'FAILED', name='verificationresult'), nullable=True, comment='验收结果'),
    sa.Column('verification_comments', sa.Text(), nullable=True, comment='验收意见'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['renovation_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renovation_attachments',
    sa.Column('id', sa.Integer(), nullable=False, comment='附件ID'),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件路径'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='文件描述'),
    sa.Column('uploaded_by', sa.Integer(), nullable=False, comment='上传人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.ForeignKeyConstraint(['task_id'], ['renovation_tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renovation_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'UPLOAD_EVIDENCE', 'SUBMIT_FOR_VERIFICATION', 'VERIFY', 'REJECT', 'CLOSE', name='renovationrecordaction'), nullable=False, comment='操作类型'),
    sa.Column('content', sa.Text(), nullable=True, comment='操作内容'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['renovation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renovation_records')
    op.drop_table('renovation_attachments')
    op.drop_table('renovation_tasks')
    op.drop_table('renovation_categories')
    # ### end Alembic commands ###
