"""add attendance_records

Revision ID: d337be6d8724
Revises: a9f18f426c1e
Create Date: 2025-08-28 11:43:37.628474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd337be6d8724'
down_revision = 'a9f18f426c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.Enum('CLOCK_IN', 'CLOCK_OUT', name='attendanceaction'), nullable=False),
    sa.Column('source', sa.Enum('WEB', 'LINE', 'API', name='attendancesource'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_timestamp'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_store_id'))

    op.drop_table('attendance_records')
    # ### end Alembic commands ###
