"""cg_bank_statement_tables

Revision ID: f66b1182829d
Revises: 63219086f39d
Create Date: 2026-02-11 16:36:56.214737

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f66b1182829d'
down_revision = '63219086f39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cg_bank_statement_files',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
                    sa.Column('storage_path', sa.String(length=512), nullable=False,
                              comment='存储相对路径（相对 static 或 upload 根）'),
                    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件哈希（如MD5）'),
                    sa.Column('bank_code', sa.String(length=32), nullable=False, comment='银行类型：BBL/KBank'),
                    sa.Column('is_encrypted', sa.Boolean(), nullable=True, comment='是否加密PDF'),
                    sa.Column('created_by', sa.Integer(), nullable=True, comment='上传人'),
                    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
                    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('cg_bank_statement_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cg_bank_statement_files_file_hash'), ['file_hash'], unique=True)

    op.create_table('cg_bank_statement_txns',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('file_id', sa.Integer(), nullable=False),
                    sa.Column('txn_date', sa.String(length=16), nullable=False, comment='日期 YYYY-MM-DD'),
                    sa.Column('txn_time', sa.String(length=16), nullable=True, comment='时间 HH:MM(:SS)'),
                    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
                    sa.Column('credit', sa.Float(), nullable=False, comment='进账金额'),
                    sa.Column('debit', sa.Float(), nullable=False, comment='出账金额'),
                    sa.Column('balance', sa.Float(), nullable=False, comment='余额'),
                    sa.Column('raw_row_hash', sa.String(length=64), nullable=False, comment='用于追溯的行hash'),
                    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
                    sa.ForeignKeyConstraint(['file_id'], ['cg_bank_statement_files.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('txn_date', 'txn_time', 'credit', 'debit', 'balance',
                                        name='uq_cg_stmt_d_t_amt_bal')
                    )
    with op.batch_alter_table('cg_bank_statement_txns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cg_bank_statement_txns_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cg_bank_statement_txns_raw_row_hash'), ['raw_row_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_cg_bank_statement_txns_txn_date'), ['txn_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cg_bank_statement_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cg_bank_statement_txns_txn_date'))
        batch_op.drop_index(batch_op.f('ix_cg_bank_statement_txns_raw_row_hash'))
        batch_op.drop_index(batch_op.f('ix_cg_bank_statement_txns_file_id'))

    op.drop_table('cg_bank_statement_txns')
    with op.batch_alter_table('cg_bank_statement_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cg_bank_statement_files_file_hash'))

    op.drop_table('cg_bank_statement_files')
    # ### end Alembic commands ###
